e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('store.urls'))
]

store/urls.py
from django.urls import path
from .views import (
    HomeView, 
    ItemView,
    checkout, 
    add_to_cart,
    remove_from_cart
)

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('checkout/', checkout, name="checkout"),
    path('product/<slug>/', ItemView.as_view(), name="product"),
    path('add-to-cart/<slug>', add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<slug>', remove_from_cart, name="remove-from-cart")
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
        ('P', 'primary'),
        ('S', 'secondary'),
        ('D', 'danger')
    )

class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField(null=True)
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={'slug':self.slug})
    
    def get_remove_form_cart_url(self):
        return reverse("remove-from-cart", kwargs={'slug':self.slug})

class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem, blank=True)
    start_date = models.DateTimeField(auto_now_add=True)
    orderd_date = models.DateTimeField(null=True)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import Item, Order, OrderItem
from django.utils import timezone
from django.contrib import messages

class HomeView(ListView):
    model = Item
    template_name = 'home-page.html'
    context_object_name = 'items'
    paginate_by = 10

class ItemView(DetailView):
    model = Item
    template_name = 'product-page.html'

def checkout(request):
    context = {
        'title': 'Checkout'
    }
    return render(request, 'checkout-page.html', context)

def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # Check if the item in order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'This item quantity add onther ')
            return redirect("product", slug=slug)
        else:
            messages.info(request, 'This item was added to your cart')
            order.items.add(order_item)
            return redirect("product", slug=slug)

    else:
        order = Order.objects.create(user=request.user, orderd_date=timezone.now())
        order.items.add(order_item)
        messages.info(request, 'A new order was create')
        return redirect("product", slug=slug)




def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # Check if the item in order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, 'This item was remove to your cart')
            return redirect("product", slug=slug)

        else:
            messages.info(request, 'This item was not in your cart')
            return redirect("product", slug=slug)

    else:
        messages.info(request, 'You dont have order ')
        return redirect("product", slug=slug)

store/templates/store/home-page.html
{% extends "store/base.html" %} {% block content %}
<!--Carousel Wrapper-->
<div
  id="carousel-example-1z"
  class="carousel slide carousel-fade pt-4"
  data-ride="carousel"
>
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li
      data-target="#carousel-example-1z"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a
    class="carousel-control-prev"
    href="#carousel-example-1z"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carousel-example-1z"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container">
    <!--Navbar-->
    <nav
      class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
    >
      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#basicExampleNav"
        aria-controls="basicExampleNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>
        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input
              class="form-control mr-sm-2"
              type="text"
              placeholder="Search"
              aria-label="Search"
            />
          </div>
        </form>
      </div>
      <!-- Collapsible content -->
    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in items %}
        <div class="col-lg-3 col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              <img
                src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg"
                class="card-img-top"
                alt=""
              />
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text"
                    >{{ item.name }}</a
                  >
                  <span
                    class="badge badge-pill {{ item.get_label_display }}-color"
                    >NEW</span
                  >
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>
                  $ {% if item.discount_price %}
                  <span>{{ item.discount_price }}</span>
                  {% else %} {{item.price}} {% endif %}
                </strong>
              </h4>
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        {% endfor %}
      </div>
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        <!--Arrow left-->
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>

        <li class="page-item active">
          <a class="page-link" href="#"
            >1
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    <!--Pagination-->
  </div>
</main>
<!--Main layout-->
{% endblock %}

store/templates/store/product-page.html
{% extends "store/base.html" %} {% block content%}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <!--Content-->
        <div class="p-4">
          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1"
                >{{ object.get_category_display }}</span
              >
            </a>
          </div>

          <p class="lead">
            {% if object.discount_price %}
            <span class="mr-1">
              <del>${{object.price}}</del>
              <span>${{ object.discount_price }}</span>
            </span>
            {% else %}
            <span>${{object.price}}</span>
            {% endif %}
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>{{ object.description}}</p>

          <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input
              type="number"
              value="1"
              aria-label="Search"
              class="form-control"
              style="width: 100px"
            />
            <button class="btn btn-primary btn-md my-0 p" type="submit">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>
          </form>
        </div>
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <hr />

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">Additional information</h4>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus
          suscipit modi sapiente illo soluta odit voluptates, quibusdam officia.
          Neque quibusdam quas a quis porro? Molestias illo neque eum in
          laborum.
        </p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
</main>
<!--Main layout-->
{% endblock %}

templates/home-page.html
{% extends "base.html" %} {% block content %}
<!--Carousel Wrapper-->
<div
  id="carousel-example-1z"
  class="carousel slide carousel-fade pt-4"
  data-ride="carousel"
>
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li
      data-target="#carousel-example-1z"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a
    class="carousel-control-prev"
    href="#carousel-example-1z"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carousel-example-1z"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container">
    <!--Navbar-->
    <nav
      class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
    >
      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#basicExampleNav"
        aria-controls="basicExampleNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>
        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input
              class="form-control mr-sm-2"
              type="text"
              placeholder="Search"
              aria-label="Search"
            />
          </div>
        </form>
      </div>
      <!-- Collapsible content -->
    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in items %}
        <div class="col-lg-3 col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              <img
                src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg"
                class="card-img-top"
                alt=""
              />
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text"
                    >{{ item.name }}</a
                  >
                  <span
                    class="badge badge-pill {{ item.get_label_display }}-color"
                    >NEW</span
                  >
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>
                  $ {% if item.discount_price %}
                  <span>{{ item.discount_price }}</span>
                  {% else %} {{item.price}} {% endif %}
                </strong>
              </h4>
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        {% endfor %}
      </div>
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number}}"
            >{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>


        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    <!--Pagination-->
  </div>
</main>
<!--Main layout-->
{% endblock %}